# Generated by Django 3.0.7 on 2020-06-10 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('class_id', models.CharField(max_length=225, unique=True)),
                ('state', models.CharField(choices=[('0', 'Online'), ('1', 'Offline')], default='1', max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='WhiteBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='white_boards', to='GiKJiK.Class')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('username', models.CharField(max_length=225, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=225)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('photo', models.ImageField(blank=True, max_length=225, upload_to='')),
                ('online_in', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='online_users', to='GiKJiK.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Quize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('q_type', models.CharField(choices=[('0', 'Multiple Choice'), ('1', 'Short Answer'), ('2', 'Both')], max_length=225)),
                ('deadline', models.DateTimeField()),
                ('state', models.CharField(choices=[('0', 'Not Overdue'), ('1', 'Overdue')], max_length=225)),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_quizes', to='GiKJiK.Class')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_quizes', to='GiKJiK.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=225)),
                ('solution', models.CharField(blank=True, max_length=225)),
                ('point', models.IntegerField()),
                ('quize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='GiKJiK.Quize')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='GiKJiK.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_grades', to='GiKJiK.Question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='std_grades', to='GiKJiK.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_classes', to='GiKJiK.UserProfile'),
        ),
        migrations.AddField(
            model_name='class',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='member_classes', to='GiKJiK.UserProfile'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ManyToManyField(blank=True, related_name='teacher_classes', to='GiKJiK.UserProfile'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=225)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='GiKJiK.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='GiKJiK.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=225)),
                ('ans_type', models.CharField(choices=[('0', 'Multiple Choice'), ('1', 'Short Answer')], max_length=225)),
                ('ans_state', models.CharField(choices=[('0', 'Correct'), ('1', 'Wrong'), ('2', 'Not Answered')], default='2', max_length=225)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to='GiKJiK.Question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='std_answers', to='GiKJiK.UserProfile')),
            ],
        ),
    ]
